# -*- coding: utf-8 -*-
"""demo_fir_lpf.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-CbWb5TRbwk9Wk3Xsi3PlEVOg_RsB3Um
"""

from scipy.signal.filter_design import sosfreqz
from scipy.signal import tf2sos
import matplotlib.pyplot as plt
import numpy as np

from scipy.signal import butter

# Butterworth filter design
b, a = butter(6, 0.125)
x = np.ones(125)

# plt.stem(x)
sos = tf2sos(b, a)
w, h = sosfreqz(sos)

plt.plot(w / np.pi, np.abs(h))
plt.show()
