# -*- coding: utf-8 -*-
"""demo_fir_lpf.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-CbWb5TRbwk9Wk3Xsi3PlEVOg_RsB3Um
"""

from scipy.signal.filter_design import sosfreqz
from scipy.signal import tf2sos
from scipy.signal import zpk2sos
import matplotlib.pyplot as plt
import numpy as np

from scipy.signal import butter

z, p, k = butter(6, 0.125, output="zpk")
x = np.ones(125)

# convert to SOS
sos = zpk2sos(z, p, k)
w, h = sosfreqz(sos)

plt.plot(w / np.pi, np.abs(h))
plt.show()
